# Generated by Django 5.2.8 on 2025-11-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroFormador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('capacidad_total', models.PositiveIntegerField()),
                ('capacidad_disponible', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completo', 'Completo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('programa', models.CharField(max_length=100)),
                ('rotacion_actual', models.CharField(max_length=100)),
                ('asistencia', models.FloatField(default=100.0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('alerta', 'Alerta'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('centro_formador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='api.centroformador')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('numero_cupos', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('solicitante', models.CharField(max_length=200)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('centro_formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centroformador')),
            ],
        ),
    ]
