# Generated by Django 5.0.14 on 2025-11-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('actividad', models.CharField(max_length=200)),
                ('centro_formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.centroformador')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.estudiante')),
            ],
        ),
    ]
