# Generated by Django 5.0.14 on 2025-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_estudiante_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='rotacion_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
