# Generated by Django 5.0.14 on 2025-11-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_estudiante_rotacion_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centroformador',
            name='capacidad_disponible',
        ),
        migrations.RemoveField(
            model_name='centroformador',
            name='capacidad_total',
        ),
        migrations.RemoveField(
            model_name='centroformador',
            name='estado',
        ),
        migrations.AddField(
            model_name='centroformador',
            name='capacidadDisponible',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad Disponible'),
        ),
        migrations.AddField(
            model_name='centroformador',
            name='capacidadTotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidad Total'),
        ),
        migrations.AddField(
            model_name='centroformador',
            name='especialidades',
            field=models.JSONField(default=list, help_text='Lista de especialidades que ofrece el centro'),
        ),
        migrations.AlterField(
            model_name='centroformador',
            name='nombre',
            field=models.CharField(help_text='Nombre del centro formador', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='centroformador',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Dirección o ciudad del centro', max_length=255),
        ),
    ]
